<?php


/**
 * Implements hook_permission().
 */
function opeka_popup_widgets_permission() {
  return array(
    'administer opeka popup widgets' => array(
      'title' => t('Administer the Opeka Popup Widgets'),
      'description' => t('Grants a user admin access to Opeka Popup Widgets.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function opeka_popup_widgets_menu() {
  $items = array();

  $items['admin/config/services/opeka_popup_widgets'] = array(
    'title' => 'Opeka Popup Widgets',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'description' => 'Provides settings for the Opeka popup widgets.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('opeka_popup_widgets_admin_form'),
    'access arguments' => array('administer opeka popup widgets'),
    'file' => 'opeka_popup_widgets.admin.inc',
  );
  return $items;
}


/**
  * Add assets - javascript variables, stylesheets etc.
  */

function opeka_popup_widgets_add_assets() {

//  $path = drupal_get_path('module', 'opeka_popup_widgets');
//
//  $opeka_screening_main = check_plain(variable_get('opeka_screening_main', ''));
//  $opeka_screening_options_array = variable_get('opeka_screening_options', []);
//  $opeka_screening_required = variable_get('opeka_screening_required', 0);
//
//  $opeka_screening_options_text_array = [];
//  foreach ($opeka_screening_options_array as $array_el) {
//    $opeka_screening_options_text_array[] = check_plain($array_el['answer_option']);
//  }

  // Settings to expose to the JavaScript client.
//  $settings['opeka_screening_main'] = $opeka_screening_main;
//  $settings['opeka_screening_options'] = $opeka_screening_options_text_array;
//  $settings['opeka_screening_required'] = $opeka_screening_required;
  // Add js files and settings
  // drupal_add_js(array('opeka_screening' => $settings), 'setting');
}
