<?php

/**
 * Implements hook_menu().
 */
function ungi_menu() {
    $items = array();

    $items['ung-i'] = array(
        'title' => 'Ung i...',
        'page callback' => 'ungi_byer',
        'description' => '',
        'access callback' => TRUE,
        'file' => 'ungi.pages.inc',
    );

    $items['ung-i/%'] = array(
        'title' => 'Ung i...',
        'page callback' => 'ungi_by',
        'page arguments' => array(1),
        'description' => '',
        'access callback' => TRUE,
        'file' => 'ungi.pages.inc',
    );

    return $items;
}

/**
 * Implements hook_theme().
 */
function ungi_theme() {
    $theme_hooks = array(
        'ungi_byer' => array(
            'template' => 'ungi-byer',
            'variables' => array('cities' => NULL),
            'path' => drupal_get_path('module', 'ungi') . '/theme',
        ),
        'ungi_by' => array(
            'template' => 'ungi-by',
            'variables' => array('city' => NULL, 'nodes' => NULL),
            'path' => drupal_get_path('module', 'ungi') . '/theme',
        ),
    );

    return $theme_hooks;
}

/**
 * Implements hook_editabletext_default_alter().
 */
function ungi_editabletext_default_alter(&$default_text, $label, $category) {
    if ($category == editabletext_get_default_category()) {
        switch ($label) {
            case 'Ung i forside':
                $default_text = '<h2>Find rådgivning i din kommune</h2>
            <p>Cyberhus samarbejder med alle kommuner i landet, men nogle af dem har vi en særlig aftale med. De kan findes på listen herunder eller ved at klikke på danmarkskortet. Under hver kommune kan du finde kommunens lokale rådgivningstilbud.</p>
            <h3>Står din kommune ikke herunder?</h3>
            <p>Så smut ind på <a href="/chat">chatten</a>, hvor vores rådgivere kan hjælpe dig med at finde den rette rådgivning nær dig.</p>
            <h3>Nyt - Den lokale chat!</h3>
            <p>Nogle kommuner har en lokal chat på Cyberhus, hvor du kan chatte helt anonymt med din kommune. Under de enkelte kommuner kan du se åbningstider for chatten.</p>
            <p>Har din kommune endnu ikke oprettet en chat, er du selvfølgelig stadig mere end velkommen til at benytte <a href="/chat">Cyberhus’ chat</a>, hvor du kan komme i kontakt med Cyberhus’ rådgivere og andre unge.</p>';
                break;

            default:
                break;
        }
    }
    return $default_text;
}

/**
 * Get the X coordinate on image
 * 
 * @param float $lng Longitude
 * @return int X coordinate on image
 */
function ungi_map_x($lng, $small = false) {
    $size = ($small) ? 312 : 445;
    if ($lng > 14.6) {
        $lng -= 2.6;
    }
    return ((($lng - 8.07) / 7.08) * $size);
}

/**
 * Get the Y coordinate on image
 * 
 * @param float $lat Latitude
 * @return int Y coordinate on image
 */
function ungi_map_y($lat, $lng, $small = false) {
    $size = ($small) ? 244 : 348;
    if ($lng > 14.6) {
        $lng -= 2.6;
        $lat += 2.3;
    }
    if ($lat == 0) {
        return 0;
    } else {
        return ($size - ((($lat - 54.55) / 3.25) * $size));
    }
}

function ungi_get_field($field) {
    if (!empty($field)) {
        $result = reset($field);
        if (!empty($result)) {
            $result = reset($result);
        }
    } else {
        $result = array();
    }
    return $result;
}

function ungi_get_field_value($field) {
    $result = ungi_get_field($field);
    if (array_key_exists('value', $result)) {
        return $result['value'];
    } else {
        return NULL;
    }
}

/*function ungi_entity_view_mode_alter(&$viewmode, $context) {
    static $term_page = FALSE;

    if ($context['entity_type'] == 'taxonomy_term') {
        if ($context['entity']->vocabulary_machine_name == 'ung_i_byer') {
            $term_page = taxonomy_term_is_page($context['entity']);
        }
    } else if ($context['entity_type'] == 'node' && $term_page) {
        //dpm($context);
        $viewmode = 'full';
    }
}
*/