name = Cybersimple
description = A simple 3 column layout for the Cyberhus Evolution theme.
preview = preview.png
template = cybersimple-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
; regions[sidebar_first]  = First sidebar
; regions[sidebar_second] = Second sidebar
regions[footer]         = Footer
regions[footer_second]    = Second Footer

; Stylesheets
stylesheets[all][] = css/layouts/cybersimple/cybersimple.layout.css
