<?php

/**
 * @file
 *
 */


/**
 * Implements hook_node_access().
 *
 * Makes sure that counselors only can edit brevkasse nodes if they
 * are tagged with the right term on their profile
 */
function cyberhus_faq_extensions_node_access($node, $op, $account) {
  if (!($node->type==='brevkasse')) {
    return NODE_ACCESS_IGNORE;
  }
  $term_match = false;
  global $user;
  $full_account = user_load($user->uid);

  $node_term = field_get_items('node', $node, 'field_base_category');
  $node_term = $node_term[0]['target_id'];
  $node_term = '2388';
  $profile_terms = field_get_items('user', $full_account, 'field_faq');

  foreach($profile_terms as $item) {
    $term_match = $item['tid'] === $node_term;
    if ($term_match) {
      break;
    }
  }
  // Brevkasserådgivere (role id=5) are denied access if node vs. profile terms aren't
  // matching. Koordinators and admins have "bypass access restrictions" permission so we don't need to // take them into account.
  if ($account->roles[5] && !$term_match && $node->type == 'brevkasse') {
    if ($op == 'update') {
      return NODE_ACCESS_DENY;
    }
  }
  return NODE_ACCESS_IGNORE;
}
